import type { NavLinkGroup } from '@/types/navigation';
import {
  BookMarked,
  BookOpen,
  Calendar,
  GraduationCap,
  Home,
  Layout,
  QrCode,
  Settings,
  TrendingUp,
  User,
  UserPlus,
  Users,
} from 'lucide-react';

export const navLinkGroups: NavLinkGroup[] = [
  {
    title: 'Panel Principal',
    icon: Home,
    links: [
      {
        href: '/dashboard',
        icon: Home,
        label: 'Inicio',
        roles: ['ADMIN', 'DOCENTE', 'ESTUDIANTE'],
        description: 'Vista general del sistema',
      },
      {
        href: '/dashboard/profile',
        icon: User,
        label: 'Perfil',
        roles: ['ADMIN', 'DOCENTE', 'ESTUDIANTE'],
        description: 'Gestiona tu información personal',
      },
    ],
  },
  {
    title: 'Área Estudiantil',
    roles: ['ESTUDIANTE'],
    icon: GraduationCap,
    links: [
      {
        href: '/dashboard/estudiante/asistencia',
        icon: QrCode,
        label: 'Asistencia',
        roles: ['ESTUDIANTE'],
        description: 'Escanear código QR para asistencia',
      },
      {
        href: '/dashboard/estudiante/historial',
        icon: TrendingUp,
        label: 'Historial de Asistencias',
        roles: ['ESTUDIANTE'],
        description: 'Consulta tus asistencias',
      },
      {
        href: '/dashboard/estudiante/escanear',
        icon: QrCode,
        label: 'Escanear',
        roles: ['ESTUDIANTE'],
        description: 'Escanear código QR para asistencia',
      },
    ],
  },
  {
    title: 'Área Docente',
    roles: ['DOCENTE'],
    icon: BookOpen,
    links: [
      {
        href: '/dashboard/docente/asignaturas',
        icon: BookMarked,
        label: 'Mis Asignaturas',
        roles: ['DOCENTE'],
        description: 'Gestiona tus asignaturas y estudiantes',
        subLinks: [
          {
            href: '/dashboard/docente/asignaturas/[id]',
            label: 'Mis Clases',
            description: 'Gestiona tus clases y eventos.',
            roles: ['DOCENTE'],
            isSubLink: true,
            parentHref: '/dashboard/docente/asignaturas/[id]',
            icon: BookMarked,
          },
          {
            href: '/dashboard/docente/asignaturas/[id]/clase/[classId]/asistencia',
            label: 'Asistencia',
            description: 'Gestiona la asistencia de tus estudiantes.',
            roles: ['DOCENTE'],
            isSubLink: true,
            parentHref: '/dashboard/docente/asignaturas/[id]/clase/[classId]/asistencia',
            icon: QrCode,
          },
        ],
      },

      {
        href: '/dashboard/docente/reportes',
        icon: TrendingUp,
        label: 'Mis Reportes',
        roles: ['DOCENTE'],
        description: 'Ver y generar reportes de asistencia',
      },
      {
        href: '/dashboard/docente/agendar',
        icon: Calendar,
        label: 'Agendar Sala',
        roles: ['DOCENTE'],
        description: 'Solicitar reserva de una sala o auditorio',
      },
    ],
  },
  {
    title: 'Administración',
    roles: ['ADMIN'],
    icon: Settings,
    links: [
      {
        href: '/dashboard/admin/usuarios',
        icon: Users,
        label: 'Gestión de Usuarios',
        roles: ['ADMIN'],
        description: 'Administrar cuentas de usuario',
        subLinks: [
          {
            href: '/dashboard/admin/docentes/cargar',
            label: 'Cargar Docentes',
            description: 'Cargar docentes desde archivo Excel',
            roles: ['ADMIN'],
            isSubLink: true,
            parentHref: '/dashboard/admin/docentes/cargar',
            icon: BookOpen,
          },
          {
            href: '/dashboard/admin/estudiantes/cargar',
            label: 'Cargar Estudiantes',
            description: 'Cargar estudiantes desde archivo Excel',
            roles: ['ADMIN'],
            isSubLink: true,
            parentHref: '/dashboard/admin/estudiantes/cargar',
            icon: GraduationCap,
          },
        ],
      },
      {
        href: '/dashboard/admin/microcurriculo',
        icon: BookMarked,
        label: 'Microcurrículo',
        roles: ['ADMIN'],
        description: 'Cargar asignaturas con información de microcurrículo',
      },
      {
        href: '/dashboard/admin/grupos',
        icon: Calendar,
        label: 'Grupos y Horarios',
        roles: ['ADMIN'],
        description: 'Crear grupos y horarios de asignaturas',
      },
      {
        href: '/dashboard/admin/matricula',
        icon: UserPlus,
        label: 'Matrícula',
        roles: ['ADMIN'],
        description: 'Matricular estudiantes en grupos',
      },
      {
        href: '/dashboard/admin/asignaturas',
        icon: BookMarked,
        label: 'Ver Asignaturas',
        roles: ['ADMIN'],
        description: 'Ver y administrar asignaturas existentes',
      },
      {
        href: '/dashboard/admin/reportes',
        icon: TrendingUp,
        label: 'Reportes Docentes',
        roles: ['ADMIN'],
        description: 'Reportes generales de docentes',
      },
      {
        href: '/dashboard/admin/salas',
        icon: Layout,
        label: 'Gestión de Salas',
        roles: ['ADMIN'],
        description: 'Administrar salas, salones y auditorios',
      },
    ],
  },
];
